### ISSUE TITLE
Feat: Enhance Destination form

### ISSUE THREAD

**Issue by pynaman** [PriyaGhosal/BuddyTrail#1448]
### Describe the feature

On the webpage https://buddytrail.netlify.app/destinationform, I want to enhance the look of Book Your Dream Destination form. I want to add few more features and give it more designs using suitable colour and background.

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-10-24 at 11 32 33 AM" src="https://github.com/user-attachments/assets/5f3e7519-27d9-4993-afb9-fcde715816c4">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dipalichourasia** [comment]
Is there an existing issue for this?
I have searched the existing issues
What happened?
Hey @PriyaGhosal
The "Destination" page doesn't look attractive .It looks very simple & I want to enhance it that's why please assign me this issue.

your current page
<img width="944" alt="Before Destination Form" src="https://github.com/user-attachments/assets/b88500c9-cea2-471f-aae0-246dc4b7902d">

Record
 I agree to follow this project's Code of Conduct
 I'm a GSSOC'24 Extended Contributor
 I want to work on this issue

**Comment by dipalichourasia** [comment]
@PriyaGhosal Please Assign me this issue

**Comment by manastiwari99** [comment]
I would like to work Please assign it to me.
